FROM ubuntu:bionic-20190204
LABEL MAINTAINER="Proffl"
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV PYTHON_PACKAGES="\
    numpy==1.16.2 pandas==0.24.1 \
    matplotlib==3.0.3 seaborn==0.9.0 missingno==0.4.1 \
    scikit-learn==0.20.3 scikit-image==0.14.2 \
    imblearn==0.0 minepy==1.2.3 lime==0.1.1.32 \
    graphviz==0.10.1 imbalanced-learn==0.4.3 shap==0.28.5 \
    statsmodels==0.9.0 xgboost==0.82 lightgbm==2.2.3 \
    jupyter jupyter_contrib_nbextensions \
    "
RUN apt-get update
RUN apt-get install -y python3
RUn apt-get install -y python3-pip
RUN pip3 install ${PYTHON_PACKAGES}

RUN jupyter_contrib_nbextensions install --user && \
    rm -rf ~/.cache